'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DETALLEEQUIPO
    Public Property Idequipo As Nullable(Of Integer)
    Public Property Iddetalle As Integer
    Public Property idpokemon As Nullable(Of Integer)

End Class
