'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class favorito
    Public Property idfavorito As Integer
    Public Property idusuario As Nullable(Of Integer)
    Public Property idpokemon As Nullable(Of Integer)



    Public Property fecha As Nullable(Of Date)
    'propiedades adicionales 
    Public Property nombre As String
    Public Property tipo As String

    Public Property ataque As String
    Public Property ataque_especial As String
    Public Property defensa As String
    Public Property defensa_especial As String
    Public Property puntovida As String
    Public Property velocidad As String

    Public Property imagen As String


End Class
