'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class FULLASSISTANCEEntities1
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=FULLASSISTANCEEntities1")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property DETALLEEQUIPO() As DbSet(Of DETALLEEQUIPO)
    Public Overridable Property equipo() As DbSet(Of equipo)
    Public Overridable Property favorito() As DbSet(Of favorito)
    Public Overridable Property usuario() As DbSet(Of usuario)

End Class
